# 公開するページのURL
baseURL = "https://sinc865p.github.io"

languageCode = "ja"
DefaultContentLanguage = "ja"
HasCJKLanguage = true
enableRobotsTXT = true

# ブログのタイトル
title = " "

theme = "mainroad"
paginate = 20

# 自己紹介
[Author]
    name = "朝比奈理比子"
    bio = "リピリピ"
    avatar = "img/profile.png"

[Params]
    customCSS = ["css/custom.css"]
    copyright = "Author"
    readmore = true
    authorbox = true
    post_meta = ["date", "categories"]
    twitter_cards = true

# ページのテーマカラー
[Params.style.vars]
  highlightColor = "#008080"

# SNS等のユーザー名
[Params.widgets.social]
  twitter = "sinc865p"

[Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

